development:
    adapter: mysql
    database: windycity_dev
    username: root
    password: 

test:
    adapter: mysql
    database: windycity_test
    username: root
    password: 
    
production:
    adapter: mysql
    database: windycity_production
    username: byennen
    password: #windy#city#17*

    
    
